import type { QueryInterface } from 'sequelize';

const ingredientIds = [
  '01M3GYH1QZKXW8T5RJ9F0C2VF1',
  '01M3GYH1QZKXW8T5RJ9F0C2VF2',
  '01M3GYH1QZKXW8T5RJ9F0C2VF3',
  '01M3GYH1QZKXW8T5RJ9F0C2VF4',
  '01M3GYH1QZKXW8T5RJ9F0C2VF5',
  '01M3GYH1QZKXW8T5RJ9F0C2VF6',
  '01M3GYH1QZKXW8T5RJ9F0C2VF7',
  '01M3GYH1QZKXW8T5RJ9F0C2VF8',
  '01M3GYH1QZKXW8T5RJ9F0C2VF9',
  '01M3GYH1QZKXW8T5RJ9F0C2VFA',
  '01M3GYH1QZKXW8T5RJ9F0C2VFB',
  '01M3GYH1QZKXW8T5RJ9F0C2VFC',
  '01M3GYH1QZKXW8T5RJ9F0C2VFD',
  '01M3GYH1QZKXW8T5RJ9F0C2VFE',
  '01M3GYH1QZKXW8T5RJ9F0C2VFF',
  '01M3GYH1QZKXW8T5RJ9F0C2VFG',
  '01M3GYH1QZKXW8T5RJ9F0C2VFH',
  '01M3GYH1QZKXW8T5RJ9F0C2VFI',
  '01M3GYH1QZKXW8T5RJ9F0C2VFJ',
  '01M3GYH1QZKXW8T5RJ9F0C2VFK',
  '01M3GYH1QZKXW8T5RJ9F0C2VFL',
  '01M3GYH1QZKXW8T5RJ9F0C2VFM',
  '01M3GYH1QZKXW8T5RJ9F0C2VFN',
  '01M3GYH1QZKXW8T5RJ9F0C2VFO',
  '01M3GYH1QZKXW8T5RJ9F0C2VFP',
  '01M3GYH1QZKXW8T5RJ9F0C2VFQ',
  '01M3GYH1QZKXW8T5RJ9F0C2VFR',
  '01M3GYH1QZKXW8T5RJ9F0C2VFS',
  '01M3GYH1QZKXW8T5RJ9F0C2VFT',
  '01M3GYH1QZKXW8T5RJ9F0C2VFU',
];

export async function up({ context }: { context: QueryInterface }) {
  const now = new Date();

  await context.bulkInsert('ingredients', [
    {
      id: ingredientIds[0],
      name: 'Espresso Coffee Beans',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[1],
      name: 'Vietnamese Coffee',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[2],
      name: 'Fresh Milk',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[3],
      name: 'Condensed Milk',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[4],
      name: 'Caramel Syrup',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[5],
      name: 'Vanilla Syrup',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[6],
      name: 'Hazelnut Syrup',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[7],
      name: 'Chocolate Sauce',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[8],
      name: 'Matcha Powder',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[9],
      name: 'Cocoa Powder',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[10],
      name: 'Milk Tea Powder',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[11],
      name: 'Brown Sugar',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[12],
      name: 'Tapioca Pearls',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[13],
      name: 'Strawberry Syrup',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[14],
      name: 'Mango Syrup',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[15],
      name: 'All-Purpose Flour',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[16],
      name: 'Butter',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[17],
      name: 'Sugar',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[18],
      name: 'Chocolate Chips',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[19],
      name: 'Cinnamon Powder',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[20],
      name: 'Banana',
      unit: 'pcs',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[21],
      name: 'Pasta',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[22],
      name: 'Parmesan Cheese',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[23],
      name: 'Bacon',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[24],
      name: 'Tomato Sauce',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[25],
      name: 'Mushrooms',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[26],
      name: 'Chicken Breast',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[27],
      name: 'Garlic',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[28],
      name: 'Cooking Cream',
      unit: 'ml',
      created_at: now,
      updated_at: now,
    },
    {
      id: ingredientIds[29],
      name: 'Mozzarella Cheese',
      unit: 'g',
      created_at: now,
      updated_at: now,
    },
  ]);
}

export async function down({ context }: { context: QueryInterface }) {
  await context.bulkDelete('ingredients', { id: ingredientIds });
}